feat(flashing): Flash RP2040 in Boot Mode
dw-0/kiauh pull request #580
Opened 2024-10-18 15:50 UTC by CODeRUS

2024-10-18 16:03 UTC, dw-0 commented
Hi, thanks for the contribution!

I was thinking about, if you could maybe add an explanation in here:
https://github.com/dw-0/kiauh/blob/develop/kiauh/components/klipper_firmware/menus/klipper_flash_help_menu.py#L140

I think it would also be cool, if you could add one for the DFU connection, as if i remember correctly, you contributed that part to KIAUH too in the past :)

2024-10-18 16:26 UTC, CODeRUS commented
@dw-0 added docs and rebased to develop

2024-10-18 16:44 UTC, dw-0 commented on kiauh/components/klipper_firmware/menus/klipper_flash_help_menu.py
> +        subheader4 = f"{COLOR_CYAN}USB RP2 Boot:{RESET_FORMAT}"
We should name it identically to the option that is selectable. So either rename the method to RP2 Boot or rename this heading to RP2040?

2024-10-18 16:44 UTC, dw-0 requested changes
Thanks for the quick update. I added one comment though.

2024-10-18 16:54 UTC, CODeRUS commented
Renamed to RP2040, RP2 Boot is just a device name identifier in boot mode.

2024-10-18 16:55 UTC, dw-0 approved these changes

2024-10-18 16:56 UTC, dw-0 commented
Thank you!

2024-10-18 16:56 UTC, merged

2024-11-27 19:59 UTC, jrsall92 commented
Hi all,

seems like I can't update klipper on an RP2040 board (the one for positron if it's relevant) unless I double press the Reset button (which forces the board into bootloader). Is there something I'm doing wrong or is this the expected behaviour? On other boards like the Prusa Buddy and the FYSETC Cheetah 2 I can simply flash via Kiauh without any issues.

2024-11-28 16:50 UTC, CODeRUS commented
@jrsall92 so what board you are talking about? Did you flashed it with zero boot offset? Also show last dmesg after executing normal flash.